version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: AUSWO
    volumes:
      - db_data:/var/lib/mysql
      - ./AUSWO_Database.sql:/docker-entrypoint-initdb.d/1.sql
      - ./AUSWO_Database_Input.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - "3306:3306"
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: test
      DB_NAME: AUSWO
      PORT: 3000
      SESSION_SECRET: GOCSPX-3p0mYH8m7VfX5d4h8j9kL0qJz9W
      GOOGLE_CLIENT_ID: 227608984263-fqq6iudhv9c71aaf61mao6t8td9m7oh7.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  db_data: