version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: AUSWO
    volumes:
      - db_data:/var/lib/mysql
      - ./AUSWO_Database.sql:/docker-entrypoint-initdb.d/1.sql
      - ./AUSWO_Database_Input.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - "3306:3306"
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: test
      DB_NAME: AUSWO
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  db_data: